trigger: none

variables:
  ARM_TENANT_ID: $(ARM_TENANT_ID)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

strategy:
  matrix: 
    job_1:
      TF_AZ_VERSION: 2.34.0
      TF_VERSION: 0.13.0
    job_2:
      TF_AZ_VERSION: 2.45.1
      TF_VERSION: 0.14.2

pool:
  vmImage: ubuntu-20.04

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make tf-install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make tf-prepare'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make tf-fmt'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make tf-init'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make tf-plan'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make tf-apply'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make tf-destroy'
  condition: always()