name: 'Test'

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  terraform:
    name: 'Test'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        terraform: [0.13.4, 0.13.5, 0.14.0]
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform }}