name: 'Tests'

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        #version: [0.12.29, 0.13.0, 0.13.5, 0.14.0]
        version: [0.13.5]
        #provider: [2.34.0, 2.35.0, 2.36.0, 2.37.0, 2.38.0, 2.39.0]
        provider: [2.39.0]
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform }}
      - name: 'Replace provider verison'
        run: |
          sed -i 's/version = ""/version = "${{ matrix.provider }}"/g' main.tf
        working-directory: './tests/deployment'
      - name: 'Initialize terraform'
        run: terraform init
        working-directory: './tests/deployment'
      - name: 'Plan terraform'
        run: terraform plan
        working-directory: './tests/deployment'
      - name: 'Replace root value'
        run: |
          sed -i 's/root_id = ""/root_id = "${{ github.run_number }}"/g' main.tf
        working-directory: './tests/deployment'
      - name: 'Apply terraform'
        run: terraform apply -auto-approve -parallelism=256
      - name: 'Destroy terraform'
        run: terraform destroy -auto-approve -parallelism=256
    env:
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}