name: 'Tests'

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        terraform: [0.12.29, 0.13.5, 0.14.0]
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
        with:
          path: source
      - name: 'Checkout template repository'
        uses: actions/checkout@v2
        with:
          repository: ljtill/cae-azscale
          path: template
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform }}
      - name: 'Initialize terraform'
        run: terraform init
        working-directory: 'template'