name: 'Tests'

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  e2e:
    name: 'E2E'
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        terraform_version: [0.12.29, 0.13.0, 0.13.5, 0.14.0]
        azurerm_version: [2.34.0, 2.35.0, 2.36.0, 2.37.0, 2.38.0, 2.39.0]
    env:
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TF_VERSION: ${{ matrix.terraform_version }}
      TF_AZ_VERSION: ${{ matrix.azurerm_version }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: '[terraform] Install'
        run: make tf-install

      - name: '[terraform] Prepare'
        run: make tf-prepare

      - name: '[terraform] Format'
        run: make tf-format

      - name: '[terraform] Initialize'
        run: make tf-init

      - name: '[terraform] Plan'
        run: make tf-plan

      - name: '[terraform] Apply'
        run: make tf-apply

      - name: '[terraform] Destroy'
        run: make tf-destroy